In [ ]:
# 파이썬에서 데이터분석 시 pandas 라이브러리를 활용
# pandas - Panel Data
# 데이터 분석 - 표 형태의 빅데이터에서 결측치와 이상치를 제거, 데이터를 가공, 정규화하여
#              데이터에서 유의미한 정보 및 지식, 지혜를 얻기 위한 작업

In [ ]:
# 최초 한 번은 pandas 라이브러리를 설치
# jupyter 셀에서 설치할 때에는 !를 붙여야 함.
# !pip install pandas

In [ ]:
# pandas 라이브러리 사용을 위해 import
# pandas 파일을 불러와서 앞으로 'pd'라는 이름으로 사용하겠다.
import pandas as pd
print(pd.__version__)

3.0.1

In [49]:
# pandas 라이브러리를 사용하면 엑셀, csv, json, dictionary 데이터를 표 형태의 데이터로 가공

# dictionary 데이터로 DataFrame 만들기
data = {
  '이름': ['김자바', '이자바', '박자바', '최캐드', '정캐드'],
  '학급': ['자바반', '자바반', '자바반', '캐드반', '캐드반'],
  '국어점수': [90, 80, 70, 100, 90],
  '영어점수': [70, 80, 80, 70, 90],
  '평균': [80.0, 80.0, 75.0, 85.0, 90.0],
  '취미': ['독서', '', '', '요가', '축구']
}

df = pd.DataFrame(data)
df.head()

    이름   학급  국어점수  영어점수    평균  취미
0  김자바  자바반    90    70 80.00  독서
1  이자바  자바반    80    80 80.00
2  박자바  자바반    70    80 75.00
3  최캐드  캐드반   100    70 85.00  요가
4  정캐드  캐드반    90    90 90.00  축구

In [ ]:
# !pip install openpyxl

In [54]:
# 위 df 데이터를 excel로 저장하기
# excel로 저장하면 df에 있던 index 정보까지 엑셀에 저장됨
# df.to_excel('test1.xlsx')

# excel 파일 저장 시 index를 제외하고 저장
df.to_excel('test2.xlsx', index=False)

In [55]:
# excel 파일 가져오기
new_df = pd.read_excel('test2.xlsx')
new_df

    이름   학급  국어점수  영어점수  평균   취미
0  김자바  자바반    90    70  80   독서
1  이자바  자바반    80    80  80  NaN
2  박자바  자바반    70    80  75  NaN
3  최캐드  캐드반   100    70  85   요가
4  정캐드  캐드반    90    90  90   축구

In [58]:
edu_df = pd.read_csv('edu_users.csv')
edu_df.head()

,rate_math,rate_science,rate_english,rate_humanities,rate_art,tot_time,device,gender,age,resub_yn,comb_yn,othersub_yn,leave_yn
0,0.38,0.80,0.83,0.90,0.39,17.09,mobile,M,30,N,N,Y,1
1,0.95,0.48,0.77,0.91,0.47,28.57,tablet,F,25,N,Y,N,1
2,0.73,0.12,0.57,0.31,0.85,40.97,tablet,F,24,N,N,N,0
3,0.60,0.12,0.96,0.69,0.34,8.09,mobile,M,14,Y,N,N,1
4,0.16,0.69,0.20,0.27,0.87,45.34,tablet,F,15,Y,N,N,0

In [60]:
edu_df1 = edu_df.copy()