In [1]:
import pandas as pd

In [ ]:
# 참: True, 거짓: False, 널데이터: None

data = {
  '학번': ['2024001', '2024002', '2024003', '2024004', '2024005',
          '2024006', '2024007', '2024008', '2024009', '2024010'],
  '이름': ['김민준', '이서연', '박지호', '최수아', '정우진',
          '강하은', '윤도현', '임지유', '한준서', '오서현'],
  '학과': ['컴퓨터공학', '정보통신', '컴퓨터공학', None, '정보통신',
          '컴퓨터공학', None, '정보통신', '컴퓨터공학', '소프트웨어'],
  '학년': [1, 2, 1, 3, 2, 1, 3, 2, 1, 3],
  '파이썬점수': [85, 92, None, 95, 88, 73, 90, None, 76, 94],
  '자바점수': [90, None, 82, 88, 92, None, 95, 78, 80, 87],
  '출석률': [95.0, 98.0, 85.0, None, 90.0, 78.0, None, 88.0, 82.0, 96.0]
}

df = pd.DataFrame(data)
df

        학번   이름     학과  학년  파이썬점수  자바점수   출석률
0  2024001  김민준  컴퓨터공학   1   85.0  90.0  95.0
1  2024002  이서연   정보통신   2   92.0   NaN  98.0
2  2024003  박지호  컴퓨터공학   1    NaN  82.0  85.0
3  2024004  최수아    NaN   3   95.0  88.0   NaN
4  2024005  정우진   정보통신   2   88.0  92.0  90.0
5  2024006  강하은  컴퓨터공학   1   73.0   NaN  78.0
6  2024007  윤도현    NaN   3   90.0  95.0   NaN
7  2024008  임지유   정보통신   2    NaN  78.0  88.0
8  2024009  한준서  컴퓨터공학   1   76.0  80.0  82.0
9  2024010  오서현  소프트웨어   3   94.0  87.0  96.0

In [4]:
df.info()
df1 = df.copy()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학번      10 non-null     str
 1   이름      10 non-null     str
 2   학과      8 non-null      str
 3   학년      10 non-null     int64
 4   파이썬점수   8 non-null      float64
 5   자바점수    8 non-null      float64
 6   출석률     8 non-null      float64
dtypes: float64(3), int64(1), str(3)
memory usage: 692.0 bytes

In [10]:
# 결측치 확인
df.isnull() # 각 데이터를 True, False로 결측치 표현

# 결측치가 있는 행만 보기
# axis=0 -> 행, axis=1 -> 열
df[df.isnull().any(axis=1)]

# 각 컬럼별 결측치 갯수 확인
df.isnull().sum()

학번       0
이름       0
학과       2
학년       0
파이썬점수    2
자바점수     2
출석률      2
dtype: int64

In [ ]:
# df의 내용을 test_df로 복사
test_df = df.copy()
test_df

        학번   이름     학과  학년  파이썬점수  자바점수   출석률
0  2024001  김민준  컴퓨터공학   1   85.0  90.0  95.0
1  2024002  이서연   정보통신   2   92.0   NaN  98.0
2  2024003  박지호  컴퓨터공학   1    NaN  82.0  85.0
3  2024004  최수아    NaN   3   95.0  88.0   NaN
4  2024005  정우진   정보통신   2   88.0  92.0  90.0
5  2024006  강하은  컴퓨터공학   1   73.0   NaN  78.0
6  2024007  윤도현    NaN   3   90.0  95.0   NaN
7  2024008  임지유   정보통신   2    NaN  78.0  88.0
8  2024009  한준서  컴퓨터공학   1   76.0  80.0  82.0
9  2024010  오서현  소프트웨어   3   94.0  87.0  96.0

In [26]:
# 결측치 제거
# dropna(axis='' how='')
# axis='index' 결측치가 있는 행 삭제 (default)
# axis='columns' 결측치가 있는 열 삭제 (axis=1과 같음)
# how='any' 결측치가 하나라도 존재하면 삭제 (default)
# how='all' 모든 데이터가 결측치 일 때 삭제

# dropna() 함수를 사용하면 결측치가 제거된 결과 데이터를 리턴, 원본 데이터는 유지
result1_df = test_df.dropna()

# 결측치가 제거된 데이터
result1_df

# test_df를 출력하면 원본 데이터 유지
test_df

# 컬럼 기준으로 결측치가 1개라도 존재하는 열을 삭제
result2_df = test_df.dropna(axis=1, how='any')
result2_df

# 특정 컬럼에 결측치가 존재하는 행만 제거
# ex> 파이썬 컬럼에 결측치가 존재하는 행 제거
result3_df = test_df.dropna(subset=['파이썬점수']) # 파이썬컬럼에 결측치가 존재하는 행 제거
result3_df

# ex> 리스트에 나열한 컬럼 중 하나라도 결측치가 포함되어 있으면 삭제
result4_df = test_df.dropna(subset=['파이썬점수', '자바점수'])
result4_df

        학번   이름     학과  학년  파이썬점수  자바점수   출석률
0  2024001  김민준  컴퓨터공학   1   85.0  90.0  95.0
3  2024004  최수아    NaN   3   95.0  88.0   NaN
4  2024005  정우진   정보통신   2   88.0  92.0  90.0
6  2024007  윤도현    NaN   3   90.0  95.0   NaN
8  2024009  한준서  컴퓨터공학   1   76.0  80.0  82.0
9  2024010  오서현  소프트웨어   3   94.0  87.0  96.0

In [ ]:
# num_cols = df1.select_dtypes(include=['number']).columns
# str_cols = df1.select_dtypes(include=['object', 'string']).columns
# df1[num_cols] = test_df1[num_cols].fillna(0)
# df1[str_cols] = df1[str_cols].fillna('빈값')

# df2 = df.copy()
# df2 = df2.fillna({
#   '학과': '알 수 없음',
#   '파이썬점수': 0.0,
#   '자바점수': 0.0,
#   '출석률': 0.0
# })

# df2

        학번   이름      학과  학년  파이썬점수  자바점수   출석률
0  2024001  김민준   컴퓨터공학   1   85.0  90.0  95.0
1  2024002  이서연    정보통신   2   92.0   0.0  98.0
2  2024003  박지호   컴퓨터공학   1    0.0  82.0  85.0
3  2024004  최수아  알 수 없음   3   95.0  88.0   0.0
4  2024005  정우진    정보통신   2   88.0  92.0  90.0
5  2024006  강하은   컴퓨터공학   1   73.0   0.0  78.0
6  2024007  윤도현  알 수 없음   3   90.0  95.0   0.0
7  2024008  임지유    정보통신   2    0.0  78.0  88.0
8  2024009  한준서   컴퓨터공학   1   76.0  80.0  82.0
9  2024010  오서현   소프트웨어   3   94.0  87.0  96.0

In [33]:
# 결측치를 특정 데이터로 대체

# 결측치를 고정값으로 대체
# ex> 학과의 결측치를 '미정'으로 채우기
test_df['학과'] = test_df['학과'].fillna('미정')
test_df

# 데이터에서 숫자 데이터의 통계 데이터 확인
test_df.describe()

# ex> 파이썬점수의 결측치를 파이썬점수의 평균으로 채우기
python_avg = test_df['파이썬점수'].mean()
test_df['파이썬점수'] = test_df['파이썬점수'].fillna(python_avg)
test_df

        학번   이름     학과  학년   파이썬점수  자바점수   출석률
0  2024001  김민준  컴퓨터공학   1  85.000  90.0  95.0
1  2024002  이서연   정보통신   2  92.000   NaN  98.0
2  2024003  박지호  컴퓨터공학   1  86.625  82.0  85.0
3  2024004  최수아     미정   3  95.000  88.0   NaN
4  2024005  정우진   정보통신   2  88.000  92.0  90.0
5  2024006  강하은  컴퓨터공학   1  73.000   NaN  78.0
6  2024007  윤도현     미정   3  90.000  95.0   NaN
7  2024008  임지유   정보통신   2  86.625  78.0  88.0
8  2024009  한준서  컴퓨터공학   1  76.000  80.0  82.0
9  2024010  오서현  소프트웨어   3  94.000  87.0  96.0

In [34]:
test_data = {
  '직원번호': ['E001', 'E002', 'E003', 'E004', 'E005',
    'E006', 'E007', 'E008', 'E009', 'E010',
    'E011', 'E012'],
  '이름': ['김태호', '이지은', '박현우', '최민서', '정다은',
    '강준혁', '윤소희', '임재원', '한지수', '오민준',
    '배수연', '신동욱'],
  '부서': ['개발', '마케팅', '개발', None, '인사',
    '개발', None, '마케팅', '인사', '개발',
    '마케팅', None],
  '직급': ['대리', '과장', '사원', '대리', '과장',
    None, '사원', '대리', None, '과장',
    '사원', '대리'],
  '연봉': [3800, 4500, 3200, None, 4200,
    3900, 3100, None, 4000, 4800,
    3300, None],
  '성과점수': [88, 92, None, 78, 95,
    None, 82, 90, 74, None,
    85, 91],
  '근속연수': [3, 7, 1, 4, 8,
    5, 2, None, 6, 9,
    None, 4]
}

In [35]:
# 1. 위 test_data를 pandas의 DataFrame으로 만드세요
t_df = pd.DataFrame(test_data)
t_df

    직원번호   이름   부서   직급      연봉  성과점수  근속연수
0   E001  김태호   개발   대리  3800.0  88.0   3.0
1   E002  이지은  마케팅   과장  4500.0  92.0   7.0
2   E003  박현우   개발   사원  3200.0   NaN   1.0
3   E004  최민서  NaN   대리     NaN  78.0   4.0
4   E005  정다은   인사   과장  4200.0  95.0   8.0
5   E006  강준혁   개발  NaN  3900.0   NaN   5.0
6   E007  윤소희  NaN   사원  3100.0  82.0   2.0
7   E008  임재원  마케팅   대리     NaN  90.0   NaN
8   E009  한지수   인사  NaN  4000.0  74.0   6.0
9   E010  오민준   개발   과장  4800.0   NaN   9.0
10  E011  배수연  마케팅   사원  3300.0  85.0   NaN
11  E012  신동욱  NaN   대리     NaN  91.0   4.0

In [38]:
# 2. 위에서 만든 DataFrame에서 컬럼별 결측치의 갯수를 파악하세요.
t_df.isnull().sum()

직원번호    0
이름      0
부서      3
직급      2
연봉      3
성과점수    3
근속연수    2
dtype: int64

In [42]:
# 3. 결측치가 있는 행만 출력하세요.
t_df[t_df.isnull().any(axis=1)]

    직원번호   이름   부서   직급      연봉  성과점수  근속연수
2   E003  박현우   개발   사원  3200.0   NaN   1.0
3   E004  최민서  NaN   대리     NaN  78.0   4.0
5   E006  강준혁   개발  NaN  3900.0   NaN   5.0
6   E007  윤소희  NaN   사원  3100.0  82.0   2.0
7   E008  임재원  마케팅   대리     NaN  90.0   NaN
8   E009  한지수   인사  NaN  4000.0  74.0   6.0
9   E010  오민준   개발   과장  4800.0   NaN   9.0
10  E011  배수연  마케팅   사원  3300.0  85.0   NaN
11  E012  신동욱  NaN   대리     NaN  91.0   4.0

In [49]:
# 4. 결측치가 하나라도 있는 행을 모두 제거하고, 몇 개의 행이 제거됐는지 출력
# 참고 > len(DataFrame) : 데이터의 갯수
original_lows = len(t_df)
r_df1 = t_df.dropna()
result_rows = original_lows - len(r_df1)
print(result_rows)

9

In [50]:
# 5. 원본데이터에서 연봉과 성과점수 중 결측치가 포함된 행을 제거
r_df2 = t_df.dropna(subset=['연봉', '성과점수'])
r_df2

    직원번호   이름   부서   직급      연봉  성과점수  근속연수
0   E001  김태호   개발   대리  3800.0  88.0   3.0
1   E002  이지은  마케팅   과장  4500.0  92.0   7.0
4   E005  정다은   인사   과장  4200.0  95.0   8.0
6   E007  윤소희  NaN   사원  3100.0  82.0   2.0
8   E009  한지수   인사  NaN  4000.0  74.0   6.0
10  E011  배수연  마케팅   사원  3300.0  85.0   NaN

In [ ]:
# 6. 아래 요구사항에 맞게 결측치를 채우세요.
#  1) 부서의 결측치는 '미배정'으로 채움
#  2) 연봉의 결측치는 연봉 평균으로 채움
#  3) 성과점수 결측치는 중앙값으로 채움
r_df3 = t_df.fillna({
  '부서': '미배정',
  '연봉': t_df['연봉'].mean(),
  '성과점수': t_df['성과점수'].median()
})

r_df3

    직원번호   이름   부서   직급           연봉  성과점수  근속연수
0   E001  김태호   개발   대리  3800.000000  88.0   3.0
1   E002  이지은  마케팅   과장  4500.000000  92.0   7.0
2   E003  박현우   개발   사원  3200.000000  88.0   1.0
3   E004  최민서  미배정   대리  3866.666667  78.0   4.0
4   E005  정다은   인사   과장  4200.000000  95.0   8.0
5   E006  강준혁   개발  NaN  3900.000000  88.0   5.0
6   E007  윤소희  미배정   사원  3100.000000  82.0   2.0
7   E008  임재원  마케팅   대리  3866.666667  90.0   NaN
8   E009  한지수   인사  NaN  4000.000000  74.0   6.0
9   E010  오민준   개발   과장  4800.000000  88.0   9.0
10  E011  배수연  마케팅   사원  3300.000000  85.0   NaN
11  E012  신동욱  미배정   대리  3866.666667  91.0   4.0

In [54]:
# 7. 결측치가 모두 처리된 데이터에서 성과점수가 90점 이상인 직원의 이름, 부서, 성과점수를 조회
r_df3[r_df3['성과점수'] >= 90][['이름', '부서', '성과점수']]

     이름   부서  성과점수
1   이지은  마케팅  92.0
4   정다은   인사  95.0
7   임재원  마케팅  90.0
11  신동욱  미배정  91.0